// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs17o_kqlIAyhteepuXsJcvUzne5jtthA',
    appId: '1:289670589097:web:a68054350d53ddc8b0d7b8',
    messagingSenderId: '289670589097',
    projectId: 'chat-app-217a5',
    authDomain: 'chat-app-217a5.firebaseapp.com',
    storageBucket: 'chat-app-217a5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA28jI0UcYHWSyGcMerAcKg9EJ8tLZN1Vo',
    appId: '1:289670589097:android:4b253c8ba51910d9b0d7b8',
    messagingSenderId: '289670589097',
    projectId: 'chat-app-217a5',
    storageBucket: 'chat-app-217a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9FzYEhoNWuajN9mMjS-68Oq9-X691smI',
    appId: '1:289670589097:ios:f7ab26dd99935128b0d7b8',
    messagingSenderId: '289670589097',
    projectId: 'chat-app-217a5',
    storageBucket: 'chat-app-217a5.appspot.com',
    iosClientId: '289670589097-1brb5c30k1349ska7ghpd8q2n6vj0j6m.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9FzYEhoNWuajN9mMjS-68Oq9-X691smI',
    appId: '1:289670589097:ios:1754de76c3231ad4b0d7b8',
    messagingSenderId: '289670589097',
    projectId: 'chat-app-217a5',
    storageBucket: 'chat-app-217a5.appspot.com',
    iosClientId: '289670589097-qur79puvdr64itps1avi80tu8lpjplqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
